#!/usr/bin/env python3
"""Generate CALIBRATION.md from the shipped configs.

The calibration report is GENERATED, never hand-written, so it cannot drift
from the constants actually in use. `kubegym verify` regenerates it and fails
if the committed file differs -- that check is the point: a paper claiming
per-constant provenance should be unable to misreport its own provenance.

Usage:
    python tools/gen_calibration_report.py            # write CALIBRATION.md
    python tools/gen_calibration_report.py --check    # exit 1 if out of date
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Any, List

from kubegym import config_path
from kubegym.provenance import ProvenancedConfig

CONFIGS = ["llm_serving_l40s.json", "request_service_default.json"]

HEADER = """# Calibration provenance

**This file is generated by `tools/gen_calibration_report.py` from the shipped configs. Do not edit
it by hand.** `kubegym verify` regenerates it and fails on any difference, so the report cannot
drift from the constants the simulator actually uses.

## How to read it

Every physical constant carries four mandatory fields and two optional flags:

| field | meaning |
|---|---|
| `value` | the constant in use |
| `calibrated` | `true` **only** if the value came from a measurement |
| `source` | how it was obtained: n, hardware, fit quality, or an explicit statement that it is a placeholder. A field without a source is refused at load time |
| `required_for_claims` | if `true`, a placeholder here makes the whole run non-reportable |
| `weak_evidence` | measured, but from too few observations to lean on |
| `flagged_optimistic` | known to bias results favourably; the source states in which direction |

**The claims gate.** A configuration reports `calibrated = false` if *any* field marked
`required_for_claims` is still a placeholder. That flag is stamped onto every result row the
environment produces, so a number carrying `calibrated=false` is a comparison inside an
uncalibrated simulator and **is not an empirical performance claim**. Nothing in the codebase
upgrades a placeholder to measured except an explicit `override(..., attest=...)` that records the
new measurement in the provenance block.

## Status summary
"""

FOOTER = """
## What a `calibrated=false` run is good for, and what it is not

It is good for *relative, paired* comparison inside the simulator: every controller faces the same
arrival and service realisation on a given episode, so a controller-versus-controller contrast is
not confounded by workload sampling. It supports statements of the form "under this model, method A
costs less than method B on this workload family, by this margin, with this dispersion".

It does **not** support statements about production behaviour. Simulation fidelity is a property of
the model structure and of the interactions between constants, not of the constants taken one at a
time, so even a fully "calibrated" configuration would not establish sim-to-real transfer. There is
no sim-to-real validation study here, and every claim is scoped to in-simulator comparison.

## The measurement campaign behind the measured constants

The constants marked measured in `llm_serving_l40s.json` come from a prior measurement campaign on a
single-GPU testbed: four co-resident vLLM replicas on one NVIDIA L40S (46 GB), vLLM 0.25.1, each
replica at `--gpu-memory-utilization 0.22`. Cold start is a median over n=9 launches; the decode
step-time model is a least-squares fit to throughput measured at batch 1, 4 and 8 (maximum relative
error 1.05% on the fit points); the KV budget was read from the engine's own reported cache size;
and the replica ceiling of 4 is the physical limit at which a fifth engine fails KV sizing.

Constants that campaign did **not** establish are labelled placeholders here rather than filled in
with plausible values. The three that matter most, all `required_for_claims`:

* `prefill_tokens_per_s` — never measured. Every time-to-first-token number is placeholder-derived.
* `decode_batch_extrapolation_above_8` — throughput was measured only to batch 8; above it the model
  extrapolates affinely. Real engines saturate, so this is **optimistic**: it makes
  under-provisioning look cheaper than it is.
* `output_length_distribution` — a labelled placeholder lognormal. This one sets the difficulty of
  the whole control problem and is the dominant uncalibrated input.

`request_service_default.json` is a modelling scaffold, not a calibrated artifact: every one of its
physical constants is a placeholder, and it is the configuration the Azure Functions corpus runs on.
Its `control_interval_s` and `n_replicas_min` are the only fields marked measured, and both are
conventions — the Kubernetes HPA default sync period, and the requirement that at least one replica
serve — rather than measurements of any service.
"""


def _flags(fl: Any) -> List[str]:
    out = []
    if fl.required_for_claims:
        out.append("required for claims")
    if fl.weak_evidence:
        out.append("weak evidence")
    if fl.flagged_optimistic:
        out.append("flagged optimistic")
    return out


def _fmt_value(v: Any) -> str:
    if isinstance(v, dict):
        head = ", ".join(f"{k}={v[k]}" for k in list(v)[:3])
        return f"`{head}`" + (" ..." if len(v) > 3 else "")
    if isinstance(v, float):
        return f"`{v:g}`"
    return f"`{v}`"


def render() -> str:
    parts = [HEADER]
    summary, bodies = [], []
    for name in CONFIGS:
        cfg = ProvenancedConfig.load(config_path(name))
        names = cfg.names()
        meas = [n for n in names if cfg.field(n).calibrated]
        req_place = list(cfg.uncalibrated_required)
        summary.append(f"| `{name}` | **{cfg.calibrated}** | {len(names)} | {len(meas)} | "
                       f"{len(names) - len(meas)} | {len(req_place)} |")
        b = [f"\n## `{name}`\n", f"Claims gate: **`calibrated = {cfg.calibrated}`**.", ""]
        if req_place:
            b.append("Blocked by these placeholder fields marked `required_for_claims`: "
                     + ", ".join(f"`{n}`" for n in req_place) + ".\n")
        b += ["| constant | value | status | flags | source |", "|---|---|---|---|---|"]
        for n in names:
            fl = cfg.field(n)
            status = "measured" if fl.calibrated else "**placeholder**"
            fg = ", ".join(_flags(fl)) or "-"
            src = (fl.source or "").replace("|", "\\|").replace("\n", " ").strip()
            extra = ""
            if fl.extra:
                bits = [f"{k}={fl.extra[k]}" for k in ("n", "iqr_s", "max_rel_err_on_fit_points")
                        if k in fl.extra]
                if bits:
                    extra = "  (" + "; ".join(bits) + ")"
            b.append(f"| `{n}` | {_fmt_value(fl.value)} | {status} | {fg} | {src}{extra} |")
        bodies.append("\n".join(b))

    parts.append("\n| config | claims gate `calibrated` | fields | measured | placeholder | "
                 "placeholders blocking claims |\n|---|---|---|---|---|---|\n"
                 + "\n".join(summary) + "\n")
    parts.extend(bodies)
    parts.append(FOOTER)
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="CALIBRATION.md")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed file differs from the regenerated one")
    a = ap.parse_args()
    text = render()
    if a.check:
        if not os.path.isfile(a.out):
            print(f"FAIL {a.out} does not exist", file=sys.stderr)
            return 1
        if open(a.out).read() != text:
            print(f"FAIL {a.out} is out of date with the shipped configs; regenerate with "
                  f"tools/gen_calibration_report.py", file=sys.stderr)
            return 1
        print(f"OK {a.out} matches the shipped configs")
        return 0
    with open(a.out, "w") as fh:
        fh.write(text)
    print(f"wrote {a.out} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
